[package]
name = "smtc_windows"
version = "0.0.0"
edition = "2021"

[lib]
name = "smtc_windows"
path = "src/lib.rs"
crate-type = ["staticlib", "cdylib"]

[[bin]]
name = "smtc_windows_bin"
path = "src/main.rs"

[build-dependencies]
flutter_rust_bridge_codegen = "1.82.*"

[dependencies]
flutter_rust_bridge = "1.82.*"
anyhow = "1.0.*"

[dependencies.windows]
version = "0.51.*"
features = ["Media", "Media_Playback", "Foundation", "Storage_Streams"]